---

- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Remove F5 ARM template deployment from Azure.  
    azure_rm_deployment:
      state: absent
      resource_group_name: bigip-rg-1
      template_link: "https://raw.githubusercontent.com/F5Networks/f5-azure-arm-templates/v5.4.0.0/supported/failover/same-net/via-api/n-nic/existing-stack/byol/azuredeploy.json"
      location: ukwest
      parameters:
        adminUsername:
          value: '{{ f5user }}'
        authenticationType:
          value: password
        adminPasswordOrKey:
          value: '{{ f5pass }}'
        dnsLabel:
          value: arch-f5
        instanceName:
          value: big-ip
        instanceType:
          value: Standard_DS3_v2
        imageName:
          value: AllTwoBootLocations
        bigIpVersion:
          value: 13.1.100000
        licenseKey1:
          value: OTSIC-HKKLK-XUDMX-YIORL-ACKYXAP
        licenseKey2:
          value: DLGRQ-KPQVB-MHSTC-FAURI-XEXYSKG
        numberOfAdditionalNics:
          value: 0
        additionalNicLocation:
          value: OPTIONAL
        numberOfExternalIps:
          value: 1
        vnetName:
          value: arch1-vnet
        vnetResourceGroupName:
          value: arch1-vnet-rg
        tenantId:
          value: '{{ az_tenantId }}'
        clientId:
          value: '{{ az_clientId }}'
        servicePrincipalSecret:
          value: '{{ az_servicePrincipalSecret }}'
        mgmtSubnetName:
          value: mgmt
        mgmtIpAddressRangeStart:
          value: 10.1.1.10
        externalSubnetName:
          value: external
        externalIpSelfAddressRangeStart:
          value: 10.1.2.10
        externalIpAddressRangeStart:
          value: 10.1.2.100
        internalSubnetName:
          value: internal
        internalIpAddressRangeStart:
          value: 10.1.3.10
        managedRoutes:
          value: 0.0.0.0/0,10.1.4.0/24,10.1.5.0/24
        ntpServer:
          value: 0.pool.ntp.org
        timeZone:
          value: UTC
        customImage:
          value: OPTIONAL 
        restrictedSrcAddress:
          value: "*"
        tagValues:
          value:
            application: APP
            cost: COST
            environment: ENV
            group: GROUP
            owner: OWNER
        allowUsageAnalytics:
          value: 'Yes'