---

- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Create Azure Deploy  
    azure_rm_deployment:
      state: present
      resource_group_name: bigip-rg-1
      template_link: "https://raw.githubusercontent.com/F5Networks/f5-azure-arm-templates/v5.4.0.0/supported/failover/same-net/via-api/n-nic/new-stack/payg/azuredeploy.json"
      location: ukwest
      parameters:
        tenantId:
          value: subscription_id
        clientId:
          value: client_id
        servicePrincipalSecret:
          value: secret
        adminUsername:
          value: FakeUsername
        adminPasswordOrKey:
          value : FakePassword
        authenticationType:
          value: password
        dnsLabel:
          value: arch-f5
        instanceName:
          value: big-ip
        instanceType:
          value: Standard_DS3_v2
        imageName:
          value: Good
        bigIpVersion:
          value: 13.1.100000
        licensedBandwidth:
          value: 200m
        licenseKey1:
          value: CESEG-XJQYJ-OBAQZ-PDVCW-TAGFSSO
        licenseKey2:
          value: IPSLL-PPNVX-OTCLQ-JYVUY-RAHMGVK
        numberOfAdditionalNics:
          value: 0
        additionalNicLocation:
          value: OPTIONAL
        numberOfExternalIps:
          value: 1
        vnetAddressPrefix:
          value: 10.1
        managedRoutes:
          value: 0.0.0.0/0,10.1.4.0/24,10.1.5.0/24
        ntpServer:
          value: 0.pool.ntp.org
        timeZone:
          value: UTC
        customImage:
          value: OPTIONAL 
        restrictedSrcAddress:
          value: "*"
        tagValues:
          value:
            application: APP
            cost: COST
            environment: ENV
            group: GROUP
            owner: OWNER
        allowUsageAnalytics:
          value: 'Yes'
